name: CI

on: [push, pull_request]

env:
  RUSTFLAGS: "-D warnings"
  RUSTDOCFLAGS: "-D warnings"
  RUST_BACKTRACE: "1"

jobs:
  ci-check:
    runs-on: ubuntu-24.04  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ci-check-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ci-check-cargo-
      - run: cargo check --locked
  unit-tests:
    runs-on: ubuntu-24.04 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ci-unit-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ci-unit-cargo-
      - run: cargo test -q --lib --bins --locked
      - run: cargo test --doc --locked
  cargo-fmt:
    runs-on: ubuntu-24.04 
    steps:
      - uses: actions/checkout@v4
      - name: Install cargo fmt
        run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
  cargo-doc-check:
    runs-on: ubuntu-24.04 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ci-doc-check-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ci-doc-check-cargo-
      - run: cargo doc --no-deps --document-private-items
