name: Doc

on:
    push: 
        branches: ["main"]

env:
  RUSTDOCFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --no-deps --document-private-items
      # https://github.com/actions/deploy-pages/issues/303#issuecomment-1951207879
      - run: rm ./target/doc/.lock
      - uses: actions/upload-pages-artifact@v4
        with:
          path: ./target/doc/
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read 
    steps:
      - name: Push to GitHub pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.DOCS_DEPLOY_TOKEN }}