name: Doc

on:
    push: 
        branches: ["main"]

env:
  RUSTDOCFLAGS: "-D warnings"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo doc --no-deps --document-private-items
      - name: Build docs
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: ./target/doc/risc_v_sim
  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push to GitHub pages
        uses: actions/deploy-pages@v4.0.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: "docs"